"""empty message

Revision ID: d12f2b6360c2
Revises: dd0eaa382d1e
Create Date: 2025-06-05 23:57:38.123656

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d12f2b6360c2"
down_revision: Union[str, None] = "dd0eaa382d1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("foodcollection", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sqlmodel.sql.sqltypes.AutoString(length=256),
            existing_nullable=False,
        )

    with op.batch_alter_table("fooditem", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sqlmodel.sql.sqltypes.AutoString(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fooditem", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=256),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    with op.batch_alter_table("foodcollection", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=256),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
