name: Lint

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
        with:
          configuration: "--profile black"
          requirements-files: "requirements.txt requirements-test.txt"